---
# Installaion of nexus server
- name: copy tar to remote host
  copy: src=../files/nexus-2.14.1-01-bundle.tar.gz dest=/tmp/nexus-2.14.1-01-bundle.tar.gz owner=root group=root mode=0750
  become: yes  

- name: download and unpack nexus
  unarchive:
    src: /tmp/nexus-2.14.1-01-bundle.tar.gz 
    dest: "{{ nexus_base }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    copy: no
    creates: "{{ nexus_home }}/bin/nexus"
  become: yes

