---
- name: install firewalld 
  yum: 
    name: firewalld 
    state: present

- name: stop firewalld
  service: name=firewalld state=stopped enabled=false
  when: ansible_distribution_major_version|int >= 7

- name: mask firewalld
  command: systemctl mask firewalld
  register: systemctl_test
  failed_when: "systemctl_test.rc != 0"
  changed_when: False
  ignore_errors: True
  when: ansible_distribution_major_version|int >= 7

- name: install iptables
  yum: name={{ item }} state=present
  with_items: "{{ iptables_packages }}"

- name: update firewall rules
  template: src={{ iptables_template }} dest=/etc/sysconfig/iptables owner=root group=root mode=0600
  notify: restart iptables

- name: Update firewall rules
  template: src={{ ip6tables_template }} dest=/etc/sysconfig/ip6tables owner=root group=root mode=0600
  notify: restart ip6tables

- name: start and enable service
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ iptables_start_enable }}"
